import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import LayoutContainer from "./LayoutContainer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <LayoutContainer>
        <body className="bg-black text-white">{children}</body>
      </LayoutContainer>
    </html>
  );
}
